---
engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  fixme:
    enabled: false
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.css"
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- "admin/languages/locale/**/*"
- "client/site/libs/**/*"
- "vendor/**/*"
